language: go

sudo: false

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - tip

branches:
    only:
        - master
        - /^v\d+\.\d+\.\d+(-\S*)?$/

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

install: make vendor

script: make test

deploy:
    provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | VERSION=v0.83.3 bash
    on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION =~ ^1\.11(\.[0-9]+)?$
