language: go

sudo: false

go:
    - 1.11.x
    - tip

branches:
    only:
        - master
        - /^v?\d+\.\d+\.\d+(-\S*)?$/

env:
    global:
        - GO111MODULE=on

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

cache:
    directories:
        - bin
        - $HOME/gopath/pkg/mod

install: go mod download

script: make test

deploy:
    provider: script
    skip_cleanup: true
    script: make release
    on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION =~ ^1\.11(\.(x|[0-9]+))?$
